language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t dockme4evr/jojo -f Dockerfile.dev .

script:
  - docker run -e CI=true dockme4evr/jojo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockerweb"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-west-2-654096695685"
  bucket_path: "dockerweb"
  on:
    branch: master  
